import Head from 'next/head'
import Login from "../components/login-btn";
import Footer from "../components/footer";
import AppInfo from "../components/appInfo";
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.main}>
      <Head>
        <title>MODU: 모두의비상금2</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scaleable=no"></meta>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossOrigin="anonymous"/>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossOrigin="anonymous"></script>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className="navbar">

        <div className="container-fluid m-3">

          <div className="Navlogo">
            <a className="navbar-brand" href="">
              <img height={30} src={`img/logo.png`} />
            </a>
          </div>

          <a className="subTitle" href="sidemenu">
            
            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" className="bi bi-list" viewBox="0 0 16 16">
              <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"/>
            </svg>

          </a>

        </div>

      </nav>

      <Login />

      <div className={styles.container}>

        <div className="row row-cols-2 row-cols-md-2 g-2">

          <div className="col">
            <div className="card text-center">
              <div className="card-body">
                  <img height={50} src={`img/ico_charge1.png`} alt="Vercel Logo"/>
                  <h5 className="card-title"><span className={styles.bannerTitle}>휴대폰 소액결제 충전</span></h5>
                  <p className="card-text"><span className={styles.bannerText}>매월 1만~75만</span></p>
              </div>
            </div>
          </div>

          <div className="col">
            <div className="card text-center">
              <div className="card-body">
                <img height={50} src={`img/ico_charge2.png`} alt="Vercel Logo"/>
                <h5 className="card-title"><span className={styles.bannerTitle}>포인트/상품권 충전</span></h5>
                <p className="card-text"><span className={styles.bannerText}>OK캐쉬백, 해피머니캐시 등</span></p>  
              </div>
            </div>
          </div>

        </div>

      </div>

      <div className="mt-3 mb-3">
        <div className={styles.container}>
          <div id="carouselExampleIndicators" className="carousel slide" data-bs-ride="true">

            <div className="carousel-indicators">

              <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" className="active" ria-current="true" aria-label="Slide 1" ></button>

            </div>

            <div className="carousel-inner">

              <div className="carousel-item active">

                <img className="d-block w-100" src={`img/img_mbanner01.png`} alt="Vercel Logo"/>

              </div>

            </div>

          </div>
        </div>
      </div>

      <div className={styles.container}>
        <div className="card">

          <ul className="list-group list-group-flush">

          <li className="m-1 list-group-item ">

            <span className="m-2">

              <img width={30} src={`img/ico_card1.png`} alt="Vercel Logo"/>

            </span>

            <span className='m-1 fw-bold'>카드신청</span>
            <span>모바일카드/실물카드 바로 신청</span>

          </li>

          <li className="m-1 list-group-item">

            <span className="m-2">

              <img width={30} src={`img/ico_card2.png`} alt="Vercel Logo"/>

            </span>

            <span className='m-1 fw-bold'>카드등록</span>
            <span>발급한 카드를 등록해 주세요</span>

          </li>

          <li className="m-1 list-group-item">
            
            <span className="m-2">

              <img width={30} src={`img/ico_chargelst.png`} alt="Vercel Logo"/>

            </span>

            <span className='m-1 fw-bold'>충전내역</span>
            <span>모두의 비상금 충전내역 확인</span>
          </li>

          <li className="m-1 list-group-item">

            <span className="m-2">
              <img width={30} src={`img/ico_faq.png`} alt="Vercel Logo"/>
            </span>

            <span className='m-1 fw-bold'>자주묻는질문</span>
            <span>무엇이 궁금하신가요?</span>

          </li>

          </ul>

        </div>


      </div>

      <AppInfo/>
      <Footer/>

    </div>
    )
}
